@api = https://steady-shrimp-32.hasura.app/v1/graphql

### 1. Consultar los Productos
POST {{api}}
Content-Type: application/json

{
  "query": "query ObtenerProductos { productos { id nombreProducto ean } }"
}

###

### 2. Consultar el Inventario y sus Movimientos
POST {{api}}
Content-Type: application/json

{
  "query": "query ObtenerInventario { inventarios { id producto { nombreProducto } bodega { nombreBodega } movimientos { cantidad fecha } } }"
}

###

### 3. Registrar un Nuevo Movimiento 

POST {{api}}
Content-Type: application/json

{
  "query": "mutation RegistrarMovimiento($invId: Int!, $cant: Int!) { insert_movimientos_one(object: {inventarioID: $invId, cantidad: $cant}) { id fecha cantidad } }",
  "variables": {
    "invId": 1,
    "cant": -5
  }
}